name: Change Root Password

on:
  workflow_dispatch:
    inputs:
      new_password:
        description: 'New password for root'
        required: true
        type: string

jobs:
  change:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Change password
        run: |
          sshpass -p "${{ secrets.GERMAN_PASS }}" ssh -t -o StrictHostKeyChecking=no root@46.225.109.36 "echo 'root:${{ github.event.inputs.new_password }}' | chpasswd"
