name: Check GOST

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check GOST version on Germany server
        uses: appleboy/ssh-action@v1
        with:
          host: 178.105.61.169
          username: root
          password: "*******"
          port: 22
          script: |
            /usr/local/bin/gost -V
