name: Save GOST Version

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Get GOST version and save locally
        uses: appleboy/ssh-action@v1
        with:
          host: 178.105.61.169
          username: root
          password: "hTuRdTssfTTu"
          port: 22
          script: |
            /usr/local/bin/gost -V
