name: Fix Germany

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Fix GOST on Germany
        uses: appleboy/ssh-action@v1
        with:
          host: 178.105.61.169
          username: root
          password: "hTuRdTssfTTu"
          port: 22
          script: |
            pkill gost
            /usr/local/bin/gost -L "tls://0.0.0.0:443" &
            sleep 2
            netstat -tlnp | grep 443
