name: Test Final

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Test
        uses: appleboy/ssh-action@v1
        with:
          host: 46.224.130.78
          username: root
          password: "KtPPWaiihK4J"
          port: 22
          script: |
            echo "Connected!"
            whoami
            pwd
