name: Test Final

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Test
        uses: appleboy/ssh-action@v1
        with:
          host: 178.105.67.21
          username: root
          password: WeJVRwwiNics9AVtcweP
          port: 22
          script: |
            echo "Connected!"
            whoami
            pwd
