name: Test Final

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Test
        uses: appleboy/ssh-action@v1
        with:
          host: 78.47.70.169
          username: root
          password: "qjUkiuMsaHJd"
          port: 22
          script: |
            echo "Connected!"
            whoami
            pwd
